# Blue(v1) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-v1-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
      version: v1
  template:
    metadata:
      labels:
        app: inventory
        version: v1
    spec:
      containers:
      - name: inventory-app
        image: withyou02/ecommerce-inventory-blue:v1
        ports:
        - containerPort: 80

---

# Green(v2) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-v2-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
      version: v2
  template:
    metadata:
      labels:
        app: inventory
        version: v2
    spec:
      containers:
      - name: inventory-app
        image: withyou02/ecommerce-inventory-green:v2
        ports:
        - containerPort: 80